export default {
  authorize: 'authorize',
  borrow: 'borrow',
  cancel: 'cancel',
  claim: 'claim',
  deployment: 'deployment',
  deposit: 'deposit',
  execution: 'execution',
  migration: 'migration',
  purchase: 'purchase',
  receive: 'receive',
  repay: 'repay',
  send: 'send',
  trade: 'trade',
  withdraw: 'withdraw',
};
